# Generated by Django 5.1 on 2024-08-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
