# Generated by Django 5.1 on 2024-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_alter_publication_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
