# Generated by Django 5.1 on 2024-08-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0003_alter_publication_date_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_text',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title',
            new_name='Titulo',
        ),
    ]
