# Generated by Django 5.1 on 2024-08-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0004_rename_author_publication_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
