# Generated by Django 5.1 on 2024-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0006_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Publications/'),
        ),
    ]
